[fix]: edited build workflow

diff --git a/.github/workflows/build.yml b/.github/workflows/build.yml
--- a/.github/workflows/build.yml
+++ b/.github/workflows/build.yml
@@ -25,33 +25,54 @@ jobs:
           version: "21"
           env: true
 
-      - name: Debug LLVM path
+      # - name: Debug LLVM path
+      #   if: runner.os == 'Windows'
+      #   run: |
+      #     echo "LLVM_PATH: " ${{ env.LLVM_PATH }}
+      #     dir "${{ env.LLVM_PATH }}"
+      #     dir "${{ env.LLVM_PATH }}/lib/cmake/llvm"
+      - name: Full Debug LLVM Structure
         if: runner.os == 'Windows'
+        shell: pwsh
         run: |
-          echo "LLVM_PATH: " ${{ env.LLVM_PATH }}
-          dir "${{ env.LLVM_PATH }}"
-          dir "${{ env.LLVM_PATH }}/lib/cmake/llvm"
+          Write-Host "Ищем все .cmake файлы в ${{ env.LLVM_PATH }}..."
+          Get-ChildItem -Path "${{ env.LLVM_PATH }}" -Filter "*.cmake" -Recurse | Select-Object FullName
 
       # - name: Configure CMake
       #   run: >
       #     cmake -B build -DCMAKE_BUILD_TYPE=${{ matrix.build_type }}
       #     -DLLVM_DIR="${{ env.LLVM_PATH }}/lib/cmake/llvm"
 
+      # - name: Configure CMake
+      #   shell: pwsh
+      #   run: |
+      #     $llvmConfigPath = Get-ChildItem -Path "${{ env.LLVM_PATH }}" -Filter "LLVMConfig.cmake" -Recurse | Select-Object -First 1 -ExpandProperty DirectoryName
+      #
+      #     if (-not $llvmConfigPath) {
+      #       Write-Error "LLVMConfig.cmake does not found in ${{ env.LLVM_PATH }}!."
+      #       exit 1
+      #     }
+      #
+      #     Write-Host "LLVM path: $llvmConfigPath"
+      #
+      #     cmake -B build `
+      #       -DCMAKE_BUILD_TYPE=${{ matrix.build_type }} `
+      #       -DLLVM_DIR="$llvmConfigPath"
       - name: Configure CMake
         shell: pwsh
         run: |
-          $llvmConfigPath = Get-ChildItem -Path "${{ env.LLVM_PATH }}" -Filter "LLVMConfig.cmake" -Recurse | Select-Object -First 1 -ExpandProperty DirectoryName
-
-          if (-not $llvmConfigPath) {
-            Write-Error "LLVMConfig.cmake does not found in ${{ env.LLVM_PATH }}!."
-            exit 1
+          $llvmConfigExe = "${{ env.LLVM_PATH }}/bin/llvm-config.exe"
+          if (Test-Path $llvmConfigExe) {
+              $llvmCmakeDir = & $llvmConfigExe --cmakedir
+              Write-Host "llvm-config сообщил путь: $llvmCmakeDir"
+          } else {
+              Write-Error "llvm-config.exe не найден по пути $llvmConfigExe"
+              exit 1
           }
-
-          Write-Host "LLVM path: $llvmConfigPath"
 
           cmake -B build `
             -DCMAKE_BUILD_TYPE=${{ matrix.build_type }} `
-            -DLLVM_DIR="$llvmConfigPath"
+            -DLLVM_DIR="$llvmCmakeDir"
 
       - name: Build
         run: >
